name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -proot" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, pdo_mysql, redis
      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Copy .env
        run: cp .env.example .env
      - name: Generate app key
        run: php artisan key:generate
      - name: Run migrations
        env:
          DB_HOST: 127.0.0.1
          DB_DATABASE: test
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan migrate --force
      - name: Build frontend
        run: |
          npm ci
          npm run build
      - name: Static analysis
        run: |
          vendor/bin/pint -v
          vendor/bin/phpstan analyse app --no-progress --memory-limit=1G
      - name: Run tests
        run: ./vendor/bin/pest -q
